### PR TITLE
Converted code to utilize new twitter archive file format

### PR DESCRIPTION
**Pull request by dannydover**
Twitter changed the file format they use for their data export/archive function from CSV to JSON. (Details available here: https://kyleconroy.com/your-twitter-data) This pull request updates the original code to parse JSON rather than CSV.

### CODE REVIEW

**Comment by denis-trofimov** [comment]
Hi!
You are wonderful guy @dannydover!
Your code has worked for me just now.
P.S. I am sad to see devs in Twitter have added this new obvious bug "ID as a float JS number" in the export data feature.

**Comment by Lewiscowles1986** [comment]
I got a CSV today. Not sure if it's all users or some, but yeah probably needs support for both.

**Comment by denis-trofimov** [comment]
@Lewiscowles1986 
1.probably a different local server, not all get updated at the same time.
2.Maybe they found a bug in JSON and rollback to CSV format?

**Comment by Lewiscowles1986** [comment]
Guys, I've read up more on this. Video record the two sessions. You're going to two similar screens which product different things. Check the URL

**Comment by koenrh** [comment]
It seems that Twitter now indeed offers two ways to export your data:
1. "Your Tweet archive" (from your [account page](https://twitter.com/settings/account)) (contains `tweets.csv`)
2. "Your Twitter data" (from your [Your Twitter data page](https://twitter.com/settings/your_twitter_data)) (contains `tweet.js`)

The first one is the one that is described in the [README](https://github.com/koenrh/delete-tweets/blob/master/README.md), and returns an archive that includes a simple CSV file containing all your tweets. The latter one returns a lot more (personal) data, and was likely introduced recently in response to new EU regulatory requirements (GDPR). I'm not sure if that option is even available to non-EU-accounts.

Could anyone of you (non-Europeans) confirm that the "[Your Twitter data](https://twitter.com/settings/your_twitter_data)" feature is accessible outside the EU?

Alternatively, we could change the script so that it takes either a path to `tweets.csv` or `tweet.js` as argument, and internally either use a CSV or JSON reader, respectively (e.g.`python deletetweets.py -d 2014-01-01 tweet.js`). What do you think?

**Comment by lalaithan** [comment]
I am outside the EU and can receive the extra data.

**Comment by koenrh** [comment]
I have updated the README to make sure people download the right archive (https://github.com/koenrh/delete-tweets/pull/10).

I prefer to keep this script as simple as possible, and only support the CSV file.

**Pull request closed without merging**
